name: fmdelivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  google_sign_in: ^5.0.4
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  flutter_easyloading: ^3.0.0
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/

